//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWhiteWings.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int LessonId { get; set; }
        public int StudentId { get; set; }
        public Nullable<bool> StudentIsBe { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Student Student { get; set; }
    }
}
